(add-to-list 'load-path "~/.emacs.d/vendor")

;;(setq custom-file "~/.emacs.d/js-packages/custom.el")
;;(load custom-file 'noerror)

(load "js-packages/better-defaults")
(load "js-packages/hackernews")
;;(load "js-packages/theme")
;;(load "js-packages/env")
(load "js-packages/global")
;;(load "js-packages/defuns")
;;(load "js-packages/bindings")
;;(load "js-packages/tabs")
;;(load "js-packages/disabled")
;;(load "js-packages/fonts")
;;(load "js-packages/utf-8")
;;(load "js-packages/scratch")
;;(load "js-packages/grep")
;;(load "js-packages/diff")
;;(load "js-packages/ido")
;;(load "js-packages/dired")
;;(load "js-packages/recentf")
;;(load "js-packages/rectangle")
;;(load "js-packages/org")
;;(load "js-packages/zoom")
;;(load "js-packages/flymake")
;;(load "js-packages/javascript")
;;(load "js-packages/ri-emacs")
;;(load "js-packages/mac")
;;(load "js-packages/server-mode")
;;(load "js-packages/shell-mode")
;;(load "js-packages/ruby-mode")
;;(load "js-packages/private" 'noerror)

;;(load "js-packages/hl-line")
;; (load "js-packages/iswitchb")

;;(vendor 'expand-region 'er/expand-region)
;;(vendor 'multiple-cursors 'mc/edit-lines 'mc/mark-next-like-this 'mc/mark-previous-like-this 'mc/mark-all-like-this 'set-rectangular-region-anchor)
;;(vendor 'jump-char     'jump-char-forward 'jump-char-backward)
;;(vendor 'rinari)
;;(vendor 'textmate)
;;(vendor 'maxframe      'mf 'maximize-frame)
;;(vendor 'filladapt)
;;(vendor 'coffee-mode)
;;(vendor 'haml-mode)
;;(vendor 'sass-mode)
;;(vendor 'htmlize)
;;(vendor 'ack-and-a-half 'ack-and-a-half 'ack-and-a-half-same 'ack-and-a-half-find-file 'ack-and-a-half-find-file-same 'ack-and-a-half-interactive)
;;(vendor 'cdargs        'cv 'cdargs)
;;(vendor 'magit         'magit-status)
;;(vendor 'psvn          'svn-status)
;;(vendor 'js2-mode      'js2-mode)
;;(vendor 'markdown-mode 'markdown-mode 'gfm-mode)
;;(vendor 'textile-mode  'textile-mode)
;;(vendor 'csv-mode      'csv-mode)
;;(vendor 'yaml-mode     'yaml-mode)
;;(vendor 'rcodetools    'xmp)
;;(vendor 'yasnippet)
;;(vendor 'jekyll)
;;(vendor 'lua-mode      'lua-mode)
;;(vendor 'feature-mode)
;;(vendor 'mode-line-bell)
;;(vendor 'revbufs       'revbufs)
;;(vendor 'shell-pop)
;;(vendor 'mo-git-blame  'mo-git-blame-file 'mo-git-blame-current)
;;(vendor 'ace-jump-mode 'ace-jump-mode 'ace-jump-word-mode 'ace-jump-char-mode 'ace-jump-line-mode)
;;(vendor 'key-chord)
;;(vendor 'bundler       'bundle-open 'bundle-console 'bundle-install 'bundle-update 'bundle-check)
;;(vendor 'browse-kill-ring+ 'browse-kill-ring)
;;(vendor 'browse-kill-ring  'NEVERLOAD-browse-kill-ring)
;;(vendor 'dired-details 'dired-details-show 'dired-details-hide 'dired-details-toggle)
;;(vendor 'dired-details+)
;;(vendor 'powerline)



;; (vendor 'ruby-electric 'ruby-electric-mode)
;; (vendor 'auctex)
